version: '3.9'

services:
  redis:
    image: redis/redis-stack-server
    container_name: 'redis-stack'
    restart: always
    ports:
      - '6379:6379'
    
    
  node:
   image:  node:19-alpine3.16
   container_name: node_serve
   restart: always
   build: .
   depends_on:
      - redis
   ports:
      - '3000:3000'

  