version: '3.9'

services:
  redis:
    image: redis/redis-stack-server
    container_name: 'redis-stack'
    restart: always
    network_mode: bridge
    expose:
      - 6379
    ports:
      - '6379:6379'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.1

  node:
    image: node:19-alpine3.16
    container_name: node_serve
    restart: always
    network_mode: bridge
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    build: .
    depends_on:
      - redis
    ports:
      - '3000:3000'
    links:
      - redis

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/29
          gateway: 10.5.0.4
