version: '3.7'

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    
  node:
   image:  node:19-alpine3.16
   container_name: node_serve
   restart: always
   build: .
   depends_on:
      - redis
   ports:
      - '3000:3000'

  